version: '3.7'
services:
    
    db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=wp
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8085:80"
      depends_on:
        - db  
      links:
        - db:db

    php:
      image: php:apache
      build: php_web
      volumes:
        - php_web:/var/www/html
      depends_on: 
        - db
        - smtp
      ports: 
        - 5000:80
    
    smtp:
      image: mailhog/mailhog
      
      ports:
        - 8025:8025  
        - 1025:1025

             
volumes: 
  db_data: {}   
  php_web: {}
     